remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: mikerobertson.info
description: fix your hearts or die

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Mike Robertson"
